name: "ll_project"
type: "python:3.12"

relationships:
    database: "postgresql:postgresql"

# The configuration of the app when it's exposed to the web.
web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET Projects/learning_log/ll_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "Projects/learning_log/static"  # Point to where static files are collected
            expires: 1h
            allow: true


# The size of the persistent disk of the application (in MB).
disk: 512

# Set a local read/write mount for logs.
mounts:
    "logs":
        source: local
        source_path: logs

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
        cd Projects/learning_log  
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        
        mkdir logs
        python manage.py collectstatic
        rm -rf logs
    deploy: |
        cd Projects/learning_log
        python manage.py migrate