# Generated by Django 5.1.2 on 2024-10-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_date_added_topping_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
